### ISSUE TITLE
Create high-level system architecture diagram.

### ISSUE THREAD

**Issue by cadezd** [ivo-hr/Dogoout#6]
Create high-level system architecture diagram and paste it in design document under high-level system architecture section. Also provide brief description of diagram.

**Comment by jsoone24** [comment]
![High_Level_System_Architecture](https://github.com/ivo-hr/Dogoout/assets/60023455/ac92b3f6-823d-4117-8b94-8953c2888a9f)

This diagram includes data flows and data structures to help understand and implement how the current system is being designed intentionally to function. Users experience easy UI/UX to find their mate. Beneath the screens, there are local databases to support automatic logins and backend codes making the app consistently connected with the Firebase so that all the information is up-to-date. Firebase is a cloud database server operating 24 hours a day making sure that the app is available all around the world.

**Comment by jsoone24** [comment]
![Dogoout_High_Level System_Architecture_v1 1-26Oct23](https://github.com/ivo-hr/Dogoout/assets/60023455/5d0c8d47-1c35-4d7c-b03d-fd688748193f)

Updated with Dogoout Logo
